environment: "stg"

track: stable

ingress:
  visibility: apigee
  apigeeAuthTlsSecret: "a/sadafaf"

autoscaling:
  horizontal:
    useHpaScaler: true

googleCloudCredentials:
  enabled: true
  appName: superSeriousApp