environment: "stg"

track: stable

ingress:
  visibility: private
  iapOauthCredentialsClientID: "asdafaf"
  iapOauthCredentialsClientSecret: "superSecret"
  apigeeAuthTlsSecret: "a/sadafaf"
  useContainerNativeLoadBalancing: true

autoscaling:
  horizontal:
    useHpaScaler: true

googleCloudCredentials:
  enabled: true
  appName: superSeriousApp

service:
#  usePrometheusProbe: false
  readiness:
    path: /actuator/health
  additionalServicePorts:
    - name: abc
      number: 8880
      protocol: TCP

deployment:
  containerPort: 8080

sidecars:
  openresty:
    enabled: false