environment: "stg"

track: stable

os: linux
releaseService: estafette

ingress:
  visibility: esp
  iapOauthCredentialsClientID: "asdafaf"
  iapOauthCredentialsClientSecret: "superSecret"
  apigeeAuthTlsSecret: "a/sadafaf"
  useContainerNativeLoadBalancing: true

autoscaling:
  horizontal:
    enabled: false

googleCloudCredentials:
  enabled: true
  appName: superSeriousApp

service:
#  usePrometheusProbe: false
  readiness:
    path: /actuator/health
  additionalPorts:
    - name: abc
      number: 8880
      protocol: TCP

deployment:
  containerPort: 8080
  additionalContainerPorts:
  - name: extra1
    port: 3333
  tolerations:
    preferPreemptibles: true
    useWindowsNodes: true
    extraTolerations:
      - key: "abc"
        operator: "myTest"
        value: "123"
        effect: "NoSchedule"
      - key: "123"
        operator: "myTest"
        value: "abc"
        effect: "NoSchedule"
  initContainers:
    - name: init-myservice
      image: busybox:1.28
      command: [ 'sh', '-c', "until nslookup myservice.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for myservice; sleep 2; done" ]
    - name: init-mydb
      image: busybox:1.28
      command: [ 'sh', '-c', "until nslookup mydb.$(cat /var/run/secrets/kubernetes.io/serviceaccount/namespace).svc.cluster.local; do echo waiting for mydb; sleep 2; done" ]
  environmentVariables:
    a: aValue
    b: bValue
  image: test
  tag: latest
  additionalVolumeMounts:
    - name: ruben-volume
      mountPath: /opt/ruben
  additionalVolumes:
    - name: ruben-volume
      hostPath:
        path: /var/ruben
        type: DirectoryOrCreate
sidecars:
  openresty:
    customProperties:
      whatever: abc
  additionalSidecars:
  - name: hello
    image: busybox
    command: [ 'sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600' ]
  - name: hello
    image: busybox
    command: [ 'sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600' ]


imagePullSecret:
  username: "u23"
  password: "123"
  email: "u23@123.com"
  registry: "gcr.io"

secrets:
  data:
    a: 23
configmaps:
  data:
    single: I only have one line
    multi: |
      I'm just a test
      and I have many lines