{{- if .Values.autoscaling.horizontal.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "estafette-application.fullname" . }}
  labels:
    {{- include "estafette-application.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "estafette-application.fullname" . }}
  minReplicas: {{ .Values.autoscaling.horizontal.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.horizontal.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.horizontal.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.autoscaling.horizontal.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.autoscaling.horizontal.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.autoscaling.horizontal.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}
