{{- if and (not $.Values.ingress.tlsSecretName) $.Values.ingress.useWildcardCertificate -}}
{{- $hostnames := include "estafette-application.hostnames" . | splitList "," -}}
{{- $internalHostnames := (include "estafette-application.internalHostnames" .) | splitList "," -}}
{{- $apigeeHostnames := include "estafette-application.apigeeHostnames" . | splitList "," -}}
{{/*  TODO fix cases when apigeeHostnames or hostnames aren't present (take conditions into account and make sure the list doesn't end with a comma*/}}
{{- $allHostnames := concat $hostnames $internalHostnames $apigeeHostnames -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $.Values.ingress.wildCardTlsSecretName }}
  labels:
    {{- include "estafette-application.labels" . | nindent 4 }}
    type: letsencrypt-certificate
  annotations:
    estafette.io/letsencrypt-certificate: "true"
    estafette.io/letsencrypt-certificate-hostnames: {{ $allHostnames | join "," | quote }}
type: Opaque
{{- end }}