{{- $visibility := $.Values.ingress.visibility | lower -}}
{{- if eq $visibility "iap" -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-iap-oauth-credentials
  labels:
    {{- include "estafette-application.labels" . | nindent 4 }}
    type: oauth-credentials
type: Opaque
data:
  client_id: {{ .Values.ingress.iapOauthCredentialsClientID | required "ingress.iapOauthCredentialsClientID is mandatory whith visibility iap" }}
  client_secret: {{ .Values.ingress.iapOauthCredentialsClientSecret | required "ingress.iapOauthCredentialsClientSecret is mandatory whith visibility iap" }}
{{ end }}