{{- if eq (include "estafette-application.usesMainIngress" .) "true" -}}
{{- $visibility := include "estafette-application.visibilityLowerCase" . -}}
{{- $hostnames := include "estafette-application.hostnames" . -}}
{{- if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
  {{- else -}}
apiVersion: extensions/v1beta1
  {{- end }}
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
  {{- include "estafette-application.labels" . | nindent 4 }}
  annotations:
    {{- if ne "iap" $visibility }}
    kubernetes.io/ingress.class: "nginx-office"
    {{- if $.Values.ingress.nginxWhitelistedIPS -}}
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ $.Values.ingress.nginxWhitelistedIPS | join "," }}
    {{- end}}
    {{- include "estafette-application.nginxCommonAnnotations" . | nindent 4 }}
    {{- include "estafette-application.nginxSslAnnotations" .  | nindent 4 }}
    {{- end }}
    estafette.io/cloudflare-dns: "true"
    estafette.io/cloudflare-proxy: {{ ne $visibility "iap" | quote }}
    estafette.io/cloudflare-hostnames: {{ $hostnames | quote }}
spec:
  tls:
    - hosts:
        {{- range splitList "," $hostnames }}
        - {{ . }}
        {{- end }}
      secretName: {{ include "estafette-application.tlsCertificateSecretName" . }}
  rules:
    {{- range splitList "," $hostnames }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $.Values.ingress.path }}
            backend:
              serviceName: {{ $.Release.Name }}
              servicePort: {{ include "estafette-application.servicePortName" $ }}
    {{- end }}
  {{- end}}