{{- if $.Values.googleCloudCredentials.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "estafette-application.googleCloudCredentialsAppName" . }}-gcp-service-account
  labels:
    {{- include "estafette-application.labels" . | nindent 4 }}
    type: gcp-service-account
  annotations:
    estafette.io/gcp-service-account: "true"
    estafette.io/gcp-service-account-name: {{ include "estafette-application.googleCloudCredentialsAppName" . | quote }}
    {{- if $.Values.googleCloudCredentials.disableServiceAccountKeyRotation }}
    estafette.io/gcp-service-account-disable-key-rotation: "true"
    {{- end}}
type: Opaque
{{- end}}