{{- if $.Values.autoscaling.vertical.enabled -}}
{{- if ne $.Values.releaseData.track "canary" -}}
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{ include "estafette-application.nameWithTrack" . }}
  labels:
    {{- include "estafette-application.labels" . | nindent 4 }}
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "estafette-application.nameWithTrack" . }}
  updatePolicy:
    updateMode: {{ $.Values.autoscaling.vertical.updateMode }}
  resourcePolicy:
    containerPolicies:
    - containerName: istio-proxy
      mode: "Off"
{{- end }}
{{- end }}