# Default values for estafette-application.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

#TODO have a look at values.schema.json
#TODO support volume mounts
#TODO revisit all labels
#TODO revisit the managed-by label
#TODO discuss need for explicit namespace (maybe flag as Helm don't delete??)
#TODO revisit app name (Release.name will collide when using canaries)
#TODO support overriding of files??
#TODO make configmap work with external directory once https://github.com/helm/helm/pull/8841 gets merged
#TODO check if we can use newer versions of k8s hpa to use CPU and/or memory
#TODO revisit version of ingress (spec has to change depending on version)


#TODO revisit this to see how Estafette can provide them (CLI --set??)
extraLabels:
  a: "1.0"

iapBackendConfigTimeout: 30
#TODO make mandatory
environment: ""
#TODO validate values
track: ""
atomicId: ""

googleCloudCredentials:
  enabled: false
  appName: ""
  #TODO support legacy file??
  disableServiceAccountKeyRotation: false

imagePullSecret:
  username: ""
  password: ""
  email: ""
  registry: ""

secrets:
  mountpath: /secrets
  data: []

configmaps:
  mountpath: /configs

deployment:
  containerPort: 5000
  secretEnvironmentVariables: []

ingress:
  visibility: private
  allowHTTP: false
  iapOauthCredentialsClientID: ""
  iapOauthCredentialsClientSecret: ""
  nginxClientBodyBufferSize: "8k"
  nginxProxyBodySize: "128m"
  nginxProxyBuffersNumber: 4
  nginxProxyBufferSize: "4k"
  nginxProxyConnectTimeout: "60"
  nginxProxySendTimeout: "60"
  nginxProxyReadTimeout: "60"
  useInternalIngress: true
  #  TODO validate values (only certain supported ones)
  nginxLoadBalanceAlgorithm: ""
  nginxWhitelistedIPS: []
  hosts: []
  internalHosts: []
  apigeeHosts: []
  useWildcardCertificate: true
  wildCardTlsSecretName: "travix-shared-wildcard-letsencrypt-certificate"
  tlsSecretName: ""
  path: "/"
  internalPath: ""
  apigeeAuthTlsSecret: ""
  apigeAuthTlsVerifyDepth: 3

service:
  type: ClusterIP
  port: 80

autoscaling:
  horizontal:
    enabled: true
    minReplicas: 3
    maxReplicas: 100
    targetCPUUtilizationPercentage: 80
    targetMemoryUtilizationPercentage: 80
    useHpaScaler: false
    hpaScalerPromQuery: ""
    hpaScalerRequestsPerReplica: 1
#    TODO revisit this value
    hpaScalerDelta: 0
    hpaScalerScaleDownMaxRatio: 1
  vertical:
    enabled: false
#    TODO validate possible values
    updateMode: "Off"

sidecars:
  openresty:
    enabled: true
  additionalSidecars: []









a:
  enabled: false
  annotations: { }
  # kubernetes.io/ingress.class: nginx
  # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: [ ]
  tls: [ ]
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

replicaCount: 1

image:
  repository: nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: { }
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: { }

podSecurityContext: { }
# fsGroup: 2000

securityContext: { }
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
# runAsNonRoot: true
# runAsUser: 1000


resources: { }
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
#   cpu: 100m
#   memory: 128Mi



nodeSelector: { }

tolerations: [ ]

affinity: { }
